highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://www.emilytiry.com/resume
author: Emily Tiry

# edit this section with your information
# for a normal use at the base of the server change it to "/"
baseurl: /resume/
title: Emily Tiry's Resume
name: Emily Tiry
email: emilytiry@gmail.com
email_full: mailto:emilytiry@gmail.com
website: emilytiry.com
website_full: https://www.emilytiry.com
github: etiry
twitter: EKTiry
#tel: +44 0000 000000
#tel_full: tel:+440000000000
#google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
#address: 44 Perth Street
#postcode: EH3 5BL
#city: Edinburgh
#country: United Kingdom
google_analytics: UA-108098167-1

# needed for travis-ci build
exclude: [vendor]
